### ISSUE TITLE
timeseries: drop "timeseries" dimension from variables to simplify downstream processing

### ISSUE THREAD

**Issue by joefutrelle** [joefutrelle/netcdf-cf-utils#4]
Since TimeseriesWriter is designed for the single timeseries case, drop the "timeseries" dimension from variables as per

https://www.nodc.noaa.gov/data/formats/netcdf/v2.0/timeSeriesOrthogonal.cdl

Which states that the timeseries dimension can be removed.

It's unclear what dimensions to use for x/y/z in this case, need further guidance.

**Comment by joefutrelle** [comment]
When I drop the timeseries dimension entirely and make all the non-time-dimensioned variables scalar, ERDDAP `GenerateDatasetsXml.sh` complains that "Station" is not an appropriate `cdm_data_type`. The fix appears to be setting the `cdm_data_type` to `TimeSeries`

**Comment by skbaum** [comment]
The allowable values for cdm_data_type via: 
http://coastwatch.pfeg.noaa.gov/erddap/download/setupDatasetsXml.html#cdm_data_type
are Point, Profile, TimeSeries, TimeSeriesProfile, Trajectory, TrajectoryProfile and Other, and what you have is a TimeSeries whose ID will be specified by the cf_role attribute for your timeseries variable.  You might want to go ahead and change the "timeseries" variable name to "station_name" as per the CF examples:

char station_name(station, name_strlen) ;
       station_name:long_name = "station name" ;
       station_name:cf_role = "timeseries_id"

with the "name_strlen" not needed if you used NetCDF4 rather than NetCDF3.
